---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: 'semver:0'
spec:
  releaseName: goldilocks
  helmVersion: v3
  rollback:
    enable: true
  chart:
    repository: https://charts.fairwinds.com/stable
    name: goldilocks
    version: 2.3.1
  values:
    installVPA: true
    dashboard:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
  valueFileSecrets:
  - name: "goldilocks-helm-values"
